server:
  port: 8086
springdoc:
  swagger-ui:
    path: /swagger-ui.html
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
discountdata:
  map:
    FURNISHING: 20.0
    KITCHENELECTRONIC: 30.0
    TOY: 10.0
    MOBILEPHONE: 50.0
    MEDICALEQUIPMENT: 50.0
    MUSICINSTRUMENT: 70.0
